obj-$(CONFIG_OPCHAIN) += uxcore/
CORE_PATH = $(KBUILD_SRC)/drivers/oneplus/coretech/uxcore/core
ifeq ($(CORE_PATH),$(wildcard $(CORE_PATH)))
obj-$(CONFIG_OPCHAIN) += uxcore/core/
endif

obj-$(CONFIG_HOUSTON) += houston/
obj-$(CONFIG_CONTROL_CENTER) += control_center/
obj-$(CONFIG_IM) += im/
obj-$(CONFIG_PCCORE) += pccore/
obj-$(CONFIG_UXCHAIN) += uxchain/
obj-$(CONFIG_TPD) += tpd/
