# oem device deriver
obj-y += input/
obj-y += kernel/
obj-y += coretech/
obj-y += fs/
obj-y += misc/
#obj-y += step_motor/
obj-y += tri_state_key/
#obj-y += vibrator/
obj-y += power/
obj-y += vibrator/
#obj-y += power/
obj-y += opslalib/
obj-y += vl53L1/
obj-y += hung_task_enhance/
